fix tests being installed on the root level
python-smpplib/python-smpplib pull request #136
Opened 2021-04-03 15:13 UTC by podshumok

See #135

2021-04-03 16:43 UTC, kousu commented
This looks good to me!

```
$ python -m virtualenv /tmp/whateiudfg
created virtual environment CPython3.9.2.final.0-64 in 169ms
  creator CPython3Posix(dest=/tmp/whateiudfg, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/kousu/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==54.1.2, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
$ . /tmp/whateiudfg/bin/activate
(whateiudfg) $ pip install git+https://github.com/podshumok/python-smpplib@fix-packaging
Collecting git+https://github.com/podshumok/python-smpplib@fix-packaging
  Cloning https://github.com/podshumok/python-smpplib (to revision fix-packaging) to /tmp/pip-req-build-a4ud55cu
  Running command git clone -q https://github.com/podshumok/python-smpplib /tmp/pip-req-build-a4ud55cu
  Running command git checkout -b fix-packaging --track origin/fix-packaging
  Switched to a new branch 'fix-packaging'
  Branch 'fix-packaging' set up to track remote branch 'fix-packaging' from 'origin'.
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Building wheels for collected packages: smpplib
  Building wheel for smpplib (setup.py) ... done
  Created wheel for smpplib: filename=smpplib-2.1.0-py3-none-any.whl size=29039 sha256=9ed1d2aff4822d0230021e5d2daf49581b4f9b40964bef2b7a85a0f2482af9c0
  Stored in directory: /tmp/pip-ephem-wheel-cache-2cosauj0/wheels/26/6d/79/df912ba9a149eae2c0512d7b63213052fa7243589951cd554a
Successfully built smpplib
Installing collected packages: six, smpplib
Successfully installed six-1.15.0 smpplib-2.1.0
(whateiudfg) [kousu@requiem ~]$ ls /tmp/whateiudfg/lib/python3.9/site-packages/smpplib
smpplib/                 smpplib-2.1.0.dist-info/ 
(whateiudfg) [kousu@requiem ~]$ cat /tmp/whateiudfg/lib/python3.9/site-packages/smpplib-2.1.0.dist-info/RECORD 
smpplib-2.1.0.dist-info/INSTALLER,sha256=zuuue4knoyJ-UwPPXg8fezS7VCrXJQrAP7zeNuwvFQg,4
smpplib-2.1.0.dist-info/LICENSE,sha256=46mU2C5kSwOnkqkw9XQAJlhBL2JAf1_uCD8lVcXyMRg,7652
smpplib-2.1.0.dist-info/METADATA,sha256=c9nmaPiZWzWORzIZazVW9vCX2nTcACDIn28IXQ0dZJw,4296
smpplib-2.1.0.dist-info/RECORD,,
smpplib-2.1.0.dist-info/REQUESTED,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
smpplib-2.1.0.dist-info/WHEEL,sha256=OqRkF0eY5GHssMorFjlbTIq072vpHpF60fIQA6lS9xA,92
smpplib-2.1.0.dist-info/direct_url.json,sha256=HbfPd-F861jQchx78vPR-3oEiVkVc7KuYjlSOOQAwNE,178
smpplib-2.1.0.dist-info/top_level.txt,sha256=H3qWYQJSYGd70RszwZRGV1MlfFH-aZ5z_LboQ1UcOTg,8
smpplib-2.1.0.dist-info/zip-safe,sha256=AbpHGcgLb-kRsJGnwFEktk7uzpZOCcBY74-YBdrKVGs,1
smpplib/__init__.py,sha256=IsNibfXn_AXnYAZcRWM36cSLhNgGyLhMhHtLbNaZcuY,958
smpplib/__pycache__/__init__.cpython-39.pyc,,
smpplib/__pycache__/client.cpython-39.pyc,,
smpplib/__pycache__/command.cpython-39.pyc,,
smpplib/__pycache__/command_codes.cpython-39.pyc,,
smpplib/__pycache__/consts.cpython-39.pyc,,
smpplib/__pycache__/exceptions.cpython-39.pyc,,
smpplib/__pycache__/gsm.cpython-39.pyc,,
smpplib/__pycache__/pdu.cpython-39.pyc,,
smpplib/__pycache__/ptypes.cpython-39.pyc,,
smpplib/__pycache__/smpp.cpython-39.pyc,,
smpplib/client.py,sha256=9yWTWusVlCNU20NSRj42s-5cXz7DitaTMur4kO7omw4,13971
smpplib/command.py,sha256=xoNgsSv69lyaDWXValq6m2z3WGYMiwZ-ZSRwdjIjt1A,34211
smpplib/command_codes.py,sha256=9cNJyROwQAFaTLwvm7BGMmm1b1UjuOdIeEjKLqX8EMM,1633
smpplib/consts.py,sha256=HLlobB8psWjlT14bknIVLUYrgK3IWznjrvpw8pTQsK8,13991
smpplib/exceptions.py,sha256=QIn2TX0XtYYS8sHdzGUKKTsRpqO3kdWl-ZaY62Zkiyk,311
smpplib/gsm.py,sha256=pG4DGHDX5cc-sHQYuW_lLMWgbt3i2Ce6aceepKqpRw8,3496
smpplib/pdu.py,sha256=FhkimxpJVbG25GHkuuRahIaSHJdFURY0QvA1hiD533g,4011
smpplib/ptypes.py,sha256=ryRmMQmXg9E8u6x6U2HaL2E_puQq7zeO3-DGoe9ZLt8,1108
smpplib/smpp.py,sha256=BAtb0SzNVu3qRM1zweRDalXja38p2rVazFTmEFVntNk,1317
smpplib/tests/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
smpplib/tests/__pycache__/__init__.cpython-39.pyc,,
smpplib/tests/__pycache__/test_client.cpython-39.pyc,,
smpplib/tests/__pycache__/test_command.cpython-39.pyc,,
smpplib/tests/__pycache__/test_gsm.cpython-39.pyc,,
smpplib/tests/test_client.py,sha256=uD0id_hVxSaVfL_RxiHeMjEA-yyHJEWE6II2F2FuBdk,1358
smpplib/tests/test_command.py,sha256=9ZolY_4cw4-ayo7ejARcZOIzprWxeNLb8IXqidO7XW0,2196
smpplib/tests/test_gsm.py,sha256=vcRbSTz5pLLyc6RgmqsPzkbEXroSdWeuslu0RmYHnuo,2197
```

The tests still don't work without your `test_requires`, so maybe they shouldn't be included in the distribution?

```
(whateiudfg) [kousu@requiem ~]$ python
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tests.test_gsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tests'
>>> import tests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tests'
>>> import smpplib.tests.test_gsm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/whateiudfg/lib/python3.9/site-packages/smpplib/tests/test_gsm.py", line 3, in <module>
    import mock
ModuleNotFoundError: No module named 'mock'
```

I was able to run them using this obscure pip syntax:

```
(whateiudfg) $ pip install 'smpplib[tests]@git+https://github.com/podshumok/python-smpplib@fix-packaging'
Collecting smpplib[tests]@ git+https://github.com/podshumok/python-smpplib@fix-packaging
  Cloning https://github.com/podshumok/python-smpplib (to revision fix-packaging) to /tmp/pip-install-fdn_nsyc/smpplib_7b81141028b846238fefb5b3cc90eed6
  Running command git clone -q https://github.com/podshumok/python-smpplib /tmp/pip-install-fdn_nsyc/smpplib_7b81141028b846238fefb5b3cc90eed6
  Running command git checkout -b fix-packaging --track origin/fix-packaging
  Switched to a new branch 'fix-packaging'
  Branch 'fix-packaging' set up to track remote branch 'fix-packaging' from 'origin'.
Requirement already satisfied: six in /tmp/whateiudfg/lib/python3.9/site-packages (from smpplib[tests]@ git+https://github.com/podshumok/python-smpplib@fix-packaging) (1.15.0)
Collecting pytest
  Using cached pytest-6.2.2-py3-none-any.whl (280 kB)
Collecting mock
  Using cached mock-4.0.3-py3-none-any.whl (28 kB)
Collecting attrs>=19.2.0
  Using cached attrs-20.3.0-py2.py3-none-any.whl (49 kB)
Collecting py>=1.8.2
  Using cached py-1.10.0-py2.py3-none-any.whl (97 kB)
Collecting toml
  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Collecting iniconfig
  Using cached iniconfig-1.1.1-py2.py3-none-any.whl (5.0 kB)
Collecting packaging
  Using cached packaging-20.9-py2.py3-none-any.whl (40 kB)
Collecting pluggy<1.0.0a1,>=0.12
  Using cached pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting pyparsing>=2.0.2
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Installing collected packages: pyparsing, toml, py, pluggy, packaging, iniconfig, attrs, pytest, mock
Successfully installed attrs-20.3.0 iniconfig-1.1.1 mock-4.0.3 packaging-20.9 pluggy-0.13.1 py-1.10.0 pyparsing-2.4.7 pytest-6.2.2 toml-0.10.2    
(whateiudfg) $ pytest -v /tmp/whateiudfg/lib/python3.9/site-packages/smpplib
============================================================================================================================== test session starts ==============================================================================================================================
platform linux -- Python 3.9.2, pytest-6.2.2, py-1.10.0, pluggy-0.13.1 -- /tmp/whateiudfg/bin/python
cachedir: .pytest_cache
rootdir: /tmp/whateiudfg/lib/python3.9/site-packages/smpplib
collected 15 items                                                                                                                                                                                                                                                         [...]

2021-04-03 16:54 UTC, podshumok commented
Thanks for the feedback.
I'm not sure about installing the test files: I do remember a couple of cases when installing tests helped to resolve some issues. In the end it's just a few text files. I guess as our tests grow we can decide at some point to not install them by default bu specifying `setup(...find_pacages=exclude...`.

2021-07-05 11:31 UTC, eigenein requested changes

2021-07-05 11:31 UTC, eigenein commented on setup.py
> -    long_description_content_type='text/markdown',
What was wrong with this?

2021-07-05 11:40 UTC, merged